apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: teams
  labels:
    name: teams
  namespace: apigee
spec:
  replicas: 1
  selector:
    matchLabels:
      component: teams
  template:
    metadata:
      labels:
        component: teams
        routable: "true"
      annotations:
        privateHosts: sso.k8s.local
        privatePaths: 3000:/teams
    spec:
      containers:
      - name: teams
        image: teams
        imagePullPolicy: IfNotPresent
        env:
          - name: PG_HOST
            value: 10.0.2.2
          - name: PG_USER
            value: martinnally
          - name: PG_PASSWORD
            value: martinnally
          - name: PG_DATABASE
            value: permissions
          - name: SPEEDUP
            value: "10" 
          - name: INTERNAL_ROUTER
            value: "internal-router" 
          - name: IPADDRESS
            valueFrom:
              fieldRef:
                fieldPath: status.podIP          
        ports:
          - containerPort: 3000